### ISSUE TITLE
'Non-existent config key: SEMISUPNET.START_UNSUP_LOSS'

### ISSUE THREAD

**Issue by xing0806** [mecarill/classawareteacher#1]
When I ran this program, it encountered an error with the following error message。
```python
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    args=(args,),
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/detectron2-0.6-py3.7-linux-x86_64.egg/detectron2/engine/launch.py", line 79, in launch
    daemon=False,
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/detectron2-0.6-py3.7-linux-x86_64.egg/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/zhuyanyan/Dehaze/class/train_net.py", line 34, in main
    cfg = setup(args)
  File "/home/zhuyanyan/Dehaze/class/train_net.py", line 26, in setup
    cfg.merge_from_file(args.config_file)
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/detectron2-0.6-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/fvcore-0.1.5.post20221221-py3.7.egg/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/yacs-0.1.8-py3.7.egg/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/yacs-0.1.8-py3.7.egg/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/zhuyanyan/anaconda3/envs/fataser/lib/python3.7/site-packages/yacs-0.1.8-py3.7.egg/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: SEMISUPNET.START_UNSUP_LOSS'

```

**Comment by mecarill** [comment]
Hi! Could you try cloning the repo again?
